### PR TITLE
User Model Refactor

### PR DESCRIPTION
**Pull request by 4rt3ry**
## Description

User services have been refactored to follow the signature `(sequelize : Sequelize) => async (service_args) => {}` to allow for unit testing with an injected custom sequelize object (no real databases involved).

User request handlers have been refactored so that every API request has a handler and controller method. The handler only deals with validation and converting data to express responses. The controller handles all main logic, service calls, and errors.

**IMPORTANT**: We use `sequelize.models` to handle database queries so `*.model.ts` files no longer need to export the model. Only the definer and model interface are needed.

### New User Schema
- Email ( **required, unique** )
- Password ( **required** )
  - 8-30 chars
  - must include lower case
  - must include upper case
  - must include a symbol/number
- Display name( **required** )
  - 1-30 chars
- **[REMOVED]** Username

### Updates
Fixed 404 message for user authentication

### CODE REVIEW

**Review by BlckHawker — CHANGES_REQUESTED** [review]
- Highly recommend looking at Travis' comments [here](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/pull/4#discussion_r1653201145) and [here](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/pull/4/files/2d0d45fc676ecafe2b9a15023dfdf5491b92f684#r1653206007), and refactoring where you see fit. Since we are using this branch as a reference, it'll be good to do quality refactoring now for one branch rather than needing to refactor 4 different ones later on. 

- Would be nice to have a `/getUser` command based on either the id or username

**Review by tstodter — APPROVED** [review]
LGTM for what it is

**Review by BlckHawker — CHANGES_REQUESTED** [review]
The only thing I think you should change is `changeDisplayName`, when you put in the same display name as your current one,  it works successfully, which is technically fine. However, doing the same thing to the password throws an error; this should be consistent. Below are other small things that I noticed, but don't need to be changed to be approved.

- Seems like `authenticate` is missing a custom 404 message.

image

- I think the `internal server error` part of the message can be omitted

image

**Comment by 4rt3ry** [comment]
> The only thing I think you should change is `changeDisplayName`, when you put in the same display name as your current one, it works successfully, which is technically fine. However, doing the same thing to the password throws an error; this should be consistent. Below are other small things that I noticed, but don't need to be changed to be approved.

That's actually intentional. I think it's fine to allow someone to change display name to the same one. I only prevent that for passwords to promote better password security.


Fixed the 404 error for authentication

**Review by BlckHawker — APPROVED** [review]

**Pull request merged**
