### PR TITLE
Database Session Storage

### PR DESCRIPTION
**Pull request by nca6109**
### Description
Created new `session` table to store session IDs of users. This table has two queries: `createSession` and `getSession`. These queries will be used to create and authenticate session IDs that match the session IDs that will be stored in a cookie by the client.

### Session Model
| Parameter | Type | Description |
| ----- | ----- | ----- |
| id | UUID | ID of the session **(Primary Key)** |
| user_id | Foreign ID of `user` | ID of the user associated with the session |
| created_at | TIMESTAMP | Time and date the session was created |
| updated_at | TIMESTAMP | Time and date the session was last updated |

#### createSession
  - Description: Create and save a session in the database for a user. Delete any other sessions associated with user
  - Query: `POST /createSession`
  - Body: `{ "user_id": 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'}`

| Parameter | Type | Description |
| ----- | ----- | ----- |
| user_id | string | ID of the user that the session is being created for |

#### getSession
  - Description: Get session data by providing a session ID (client stores this session ID as a cookie to authenticate after login)
  - Query: `GET /getSession/:id`

| Parameter | Type | Description |
| ----- | ----- | ----- |
| id | string | ID of the session to get information from |

### CODE REVIEW

**Review by BlckHawker — CHANGES_REQUESTED** [review]
a

**Review by BlckHawker — COMMENTED** [review]
Small change. This error message can be changed to "A session with an id of {insert id} doesn't exist". This is when you give an invalid id
image

**Comment by nca6109** [comment]
> Small change. This error message can be changed to "A session with an id of {insert id} doesn't exist". This is when you give an invalid id image

It seems that this error is occurring because the data entered isn't in a valid UUID format, not because there isn't a session with the UUID. Would you like me to add a specific catch for entering data in an incorrect format or does the default error message give enough info about that?

**Review by BlckHawker — APPROVED** [review]
I looked at how get user works and it returns the same error message. You can disregard what I said before

**Pull request merged**
